### ISSUE TITLE
Add labels option

### ISSUE THREAD

**Issue by ybiquitous** [ybiquitous/npm-audit-fix-action#152]
For example:

```yaml
steps:
  - uses: ybiquitous/npm-audit-fix-action@v1
    with:
      labels: [dependencies, security]
```
